In [25]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [26]:
df100 = pd.read_csv("data/1.0.csv")
df131 = pd.read_csv("data/1.31.csv")
df132 = pd.read_csv("data/1.32.csv")

In [27]:
print 'df100.head()='
df100.head()

df100.head()=

,id,serverTime,userTime,gameVersion,playerId,playerBirthdate,playerRegion,playerCountry,playerGender,playerExternalId,playerCustomData,type,coordinates,section,customData
0,ec294932-22e7-4e32-8074-54ba6755f2d2,2015-04-17T20:52:31.974Z,NaN,99a00e65-6039-41a3-a85b-360c4b30a466,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,NaN,NaN,NaN,NaN,NaN,NaN,start,NaN,NaN,NaN
1,fdcd8995-ea75-465d-bf97-58c2e0f1df0d,2015-04-17T23:04:30.701Z,NaN,99a00e65-6039-41a3-a85b-360c4b30a466,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,NaN,NaN,NaN,NaN,NaN,NaN,start,NaN,NaN,NaN
2,c382b93e-b11c-424e-9bab-67803d47f352,2015-04-17T23:21:24.426Z,NaN,99a00e65-6039-41a3-a85b-360c4b30a466,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,NaN,NaN,NaN,NaN,NaN,NaN,start,NaN,NaN,NaN
3,4e99e89d-1285-4215-8f53-088ddc5d5bf3,2015-04-18T00:22:20.163Z,NaN,99a00e65-6039-41a3-a85b-360c4b30a466,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,NaN,NaN,NaN,NaN,NaN,NaN,todelete,NaN,NaN,NaN
4,45837197-12f2-40e1-81e8-2534cac88621,2015-04-18T00:32:11.358Z,NaN,99a00e65-6039-41a3-a85b-360c4b30a466,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,NaN,NaN,NaN,NaN,NaN,NaN,todelete,NaN,NaN,NaN

In [28]:
print 'df131.head()='
df131.head()

df131.head()=

,id,serverTime,userTime,gameVersion,playerId,playerBirthdate,playerRegion,playerCountry,playerGender,playerExternalId,playerCustomData,type,coordinates,section,customData
0,43499a88-6182-473a-b21a-3d80fcd07171,2015-05-20T12:32:27.329Z,2015-05-20T12:32:28.371Z,5832732e-6bfb-4ac7-8df4-270c6f20b72a,652c4bb8-faed-446f-9c29-ca7a4e0e9dd6,NaN,NaN,NaN,NaN,NaN,NaN,reached,NaN,Checkpoint01,NaN
1,5b6bbd69-dbb8-4fb1-b6c4-8f306c3f322f,2015-05-20T12:32:32.301Z,2015-05-20T12:32:32.530Z,5832732e-6bfb-4ac7-8df4-270c6f20b72a,652c4bb8-faed-446f-9c29-ca7a4e0e9dd6,NaN,NaN,NaN,NaN,NaN,NaN,start,NaN,Checkpoint01,NaN
2,16842105-c07b-4014-94f0-8026b9c7ea80,2015-05-20T12:32:37.316Z,2015-05-20T12:32:36.253Z,5832732e-6bfb-4ac7-8df4-270c6f20b72a,652c4bb8-faed-446f-9c29-ca7a4e0e9dd6,NaN,NaN,NaN,NaN,NaN,NaN,death,NaN,Checkpoint01,NaN
3,5018840b-ef77-4b71-9584-dc7d5fc61f9f,2015-05-20T12:32:42.299Z,2015-05-20T12:32:41.104Z,5832732e-6bfb-4ac7-8df4-270c6f20b72a,652c4bb8-faed-446f-9c29-ca7a4e0e9dd6,NaN,NaN,NaN,NaN,NaN,NaN,pickup,NaN,Checkpoint01,"""PRCONS:RBS2:MOV:DTER"""
4,336be39a-780f-447e-8008-5e5e375e5b8c,2015-05-20T12:32:47.317Z,2015-05-20T12:32:46.349Z,5832732e-6bfb-4ac7-8df4-270c6f20b72a,652c4bb8-faed-446f-9c29-ca7a4e0e9dd6,NaN,NaN,NaN,NaN,NaN,NaN,equip,NaN,Checkpoint01,"""PRCONS:RBS2:MOV:DTER"""

In [29]:
print 'df132.head()='
df132.head()

df132.head()=

,id,serverTime,userTime,gameVersion,playerId,playerBirthdate,playerRegion,playerCountry,playerGender,playerExternalId,...,type,coordinates,section,customData.language,customData.controls,customData.device,customData.sound,customData.gamelevel,customData,customData.dnabit
0,13815a6e-da1d-4b1d-862f-6e394a4cec98,2015-09-10T12:32:45.204Z,2015-09-10T12:32:48.469Z,be209fe8-0ef3-4291-a5f4-c2b389f5d77d,2bb4a2ab-eaf1-4e0e-b2fe-5f5e88248733,NaN,NaN,NaN,NaN,NaN,...,start,"[-6, 143]",NaN,NaN,NaN,NaN,NaN,NaN,null,NaN
1,36963346-0445-45ce-bad0-b767325becb2,2015-09-10T12:32:45.212Z,2015-09-10T12:32:48.481Z,be209fe8-0ef3-4291-a5f4-c2b389f5d77d,8565a7b9-811b-4b56-9cae-c7eeb28314d7,NaN,NaN,NaN,NaN,NaN,...,start,"[-6, 143]",NaN,NaN,NaN,NaN,NaN,NaN,null,NaN
2,7705c2aa-1de0-40c2-8cea-71e60b326f54,2015-09-10T12:33:35.665Z,2015-09-10T12:33:38.935Z,be209fe8-0ef3-4291-a5f4-c2b389f5d77d,8565a7b9-811b-4b56-9cae-c7eeb28314d7,NaN,NaN,NaN,NaN,NaN,...,reach,"[-6, 134]",Checkpoint01,NaN,NaN,NaN,NaN,NaN,null,NaN
3,b327e325-bf7d-4ecc-9c7c-ab9b3894eedd,2015-09-10T13:41:43.245Z,2015-09-10T13:41:46.501Z,be209fe8-0ef3-4291-a5f4-c2b389f5d77d,4d9c1137-d582-4333-b264-e59eebd2b6d8,NaN,NaN,NaN,NaN,NaN,...,start,"[-6, 143]",NaN,NaN,NaN,NaN,NaN,NaN,null,NaN
4,d00eb541-9be1-4483-b622-f72b30507adb,2015-09-10T13:41:53.529Z,2015-09-10T13:41:56.785Z,be209fe8-0ef3-4291-a5f4-c2b389f5d77d,4d9c1137-d582-4333-b264-e59eebd2b6d8,NaN,NaN,NaN,NaN,NaN,...,reach,"[-4, 134]",Checkpoint01,NaN,NaN,NaN,NaN,NaN,null,NaN

# Accumulation Test

In [32]:
relevantColumns = ['serverTime', 'playerId', 'type', 'section']

df = df100.loc[:,relevantColumns]
part131 = df131.loc[:,relevantColumns]
part132 = df132.loc[:,relevantColumns]

df = pd.concat([df, part131, part132])

df.head()

,serverTime,playerId,type,section
0,2015-04-17T20:52:31.974Z,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,start,NaN
1,2015-04-17T23:04:30.701Z,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,start,NaN
2,2015-04-17T23:21:24.426Z,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,start,NaN
3,2015-04-18T00:22:20.163Z,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,todelete,NaN
4,2015-04-18T00:32:11.358Z,b5ab445a-56c9-4c5b-a6d0-86e8a286cd81,todelete,NaN